name: crescendonoesporte
description: Aplicativo para controle do projeto social

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.3
  csv: ^5.0.0
  permission_handler: ^7.1.0
  filesystem_picker: ^2.0.0-nullsafety.0
  share: ^2.0.4
  mobx: ^2.0.4
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  firebase_core: ^1.7.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"